### ISSUE TITLE
find fails with array of ids

### ISSUE THREAD

**Issue by zyphrus** [jcypret/hashid-rails#20]
The default behaviour of [`Model#find`](http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find) is to take a single id and returns a single element or take
an array of ids and returns an array of elements (though duplicate ids in the array are not in the result).

## Expected behaviour:

using the code below will work with `hashid-rails` installed

```ruby
Model.find([1,2])
=> [#<Model id: 1>,  #<Model id: 2>]
```

## Actual Result

Get an error
```
ActiveRecord::RecordNotFound: Couldn't find Role without an ID
        from /Users/drb/.gem/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/relation/finder_methods.rb:454:in `find_with_ids'
        from /Users/drb/.gem/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/relation/finder_methods.rb:66:in `find'
        from /Users/drb/.gem/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/querying.rb:3:in `find'
        from /Users/drb/.gem/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/core.rb:151:in `find'
        from /Users/drb/.gem/ruby/2.3.0/gems/hashid-rails-0.5.0/lib/hashid/rails.rb:66:in `find'
        from (irb):1
        from /Users/drb/.gem/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/console.rb:65:in `start'
        from /Users/drb/.gem/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/console_helper.rb:9:in `start'
        from /Users/drb/.gem/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
        from /Users/drb/.gem/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /Users/drb/.gem/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
        from /Users/drb/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
        from /Users/drb/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
        from /Users/drb/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
        from /Users/drb/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
        from /Users/drb/Code/project/mafia-rails/bin/rails:9:in `<top (required)>'
        from /Users/drb/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
        from /Users/drb/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `block in load'
        from /Users/drb/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
        from /Users/drb/.gem/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
        from /Users/drb/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/drb/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'
```

## Environment

This was found to occur on Ruby on Rails 5.0.1 and ruby 2.3.3 on macOS

**Comment by jcypret** [comment]
Hi @zyphrus. Thanks for pointing this out! I was able to replicate the issue you mentioned, added a test case, and implemented a fix in version 0.6.0 (https://github.com/jcypret/hashid-rails/commit/23caa2228d6c345050040f6287a7dd33d1aadf51).
